services:
  api:
    build:
      context: .
      dockerfile: FireFishPortfolioManager.Api/Dockerfile
    ports:
      - "7227:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=tcp:firefish-sql-server.database.windows.net,1433;Database=FireFishDB;User ID=serveradmin;Password=ComplexPassword123!;Encrypt=true;Connection Timeout=30;
    networks:
      - firefish-network

  client:
    build:
      context: .
      dockerfile: firefishportfoliomanager-client/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:7227
    networks:
      - firefish-network

networks:
  firefish-network:
    driver: bridge
